## Docker compose - orquestrador de container

# Versão para o docker-compose
version: '3.7'

## Serviços que vamos rodar
# Serviço para orquestrar a imagem que criamos - docker run -p 3333:3333 rentalx
services:
  database_ignite: 
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentalx
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentalx
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app 
    links:
      - database_ignite
    depends_on:
      - database_ignite

volumes:
  pgdata: 
    driver: local


## Para executar o docker-compose
# docker-compose up

## Para executar o docker-compose em background
# docker-compose up -d

## Para executar o docker-compose e forçar a criaçã do container dnv
# docker-compose up --force-recreate 


## Para pausar o docker-compose
# docker-compose stop

## Remover docker-compose
# docker-compose down

## Para o hot reload funcionar é nescessário possuir --poll no script de startar a aplicação

## Para ver o ip que está rodando o serviço
# docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' database_ignite
# docker exec rentalx cat /etc/hots

