## Docker compose - orquestrador de container

# Versão para o docker-compose
version: '3.7'

## Serviços que vamos rodar
# Serviço para orquestrar a imagem que criamos - docker run -p 3333:3333 rentalx
services:
  app:
    build: .
    container_name: rentalx
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app 


## Para executar o docker-compose
# docker-compose up

## Para executar o docker-compose em background
# docker-compose up -d

## Para pausar o docker-compose
# docker-compose stop

## Remover docker-compose
# docker-compose down

## Para o hot reload funcionar é nescessário possuir --poll no script de startar a aplicação

